export const emptyRoutesTemplate = `// Auto-generated by olova-router - DO NOT EDIT
import type { ComponentType } from 'react';

export interface Route {
  path: string;
  component: ComponentType;
}

export const routes: Route[] = [];

export type RoutePaths = never;
`;
