export function generateRoutesTemplate(
  imports: string,
  routeObjects: string,
  routePaths: string
): string {
  return `// Auto-generated by olova-router - DO NOT EDIT
import type { ComponentType } from 'react';

${imports}

export interface Route {
  path: string;
  component: ComponentType;
}

export const routes: Route[] = [
${routeObjects}
];

export type RoutePaths = ${routePaths};
`;
}
