// Auto-generated by olova-router - DO NOT EDIT
// This file is auto-updated when you add/remove route folders

import { createLink, OlovaRouter, useRouter, useParams, useSearchParams, usePathname, Outlet, clientOnly, useLoaderData, useActionData, usePending, useIsLoading, useIsSubmitting, useLoaderError, useSubmit, defer, Await, prefetch, invalidateLoader, invalidateAll, useInvalidate, useRouteContext, useRevalidate } from 'olova-router/router';
import Route0 from './App';
import * as RouteModule1 from './about/index';
import * as RouteModule2 from './(auth)/login/index';
import Route3 from './(auth)/register/index';
import * as RouteModule4 from './search/index';
import Route5 from './users/index';
import Route6 from './blog/$/index';
import Route7 from './users/$id/index';
import NotFound0 from './404';
import Layout0 from './_layout';

export const routes = [
  { path: '/', component: Route0 },
  { path: '/about', component: RouteModule1.default, metadata: RouteModule1.metadata, routeDefinition: RouteModule1.route },
  { path: '/login', component: RouteModule2.default, metadata: RouteModule2.metadata },
  { path: '/register', component: Route3 },
  { path: '/search', component: RouteModule4.default, metadata: RouteModule4.metadata },
  { path: '/users', component: Route5 },
  { path: '/blog/*', component: Route6 },
  { path: '/users/:id', component: Route7 }
];

export const notFoundPages = [
  { pathPrefix: '', component: NotFound0 }
];

export const layouts = [
  { path: '/', layout: Layout0, children: [] }
];

export type RoutePaths = '/' | '/about' | '/login' | '/register' | '/search' | '/users' | '/blog/*' | '/users/:id';

export const Link = createLink<RoutePaths>();
export { OlovaRouter, useRouter, useParams, useSearchParams, usePathname, Outlet, clientOnly, useLoaderData, useActionData, usePending, useIsLoading, useIsSubmitting, useLoaderError, useSubmit, defer, Await, prefetch, invalidateLoader, invalidateAll, useInvalidate, useRouteContext, useRevalidate };
export type { NotFoundPageConfig, SearchParams, SetSearchParamsOptions, LayoutRoute, Metadata, RouteDefinition, LoaderContext, ActionContext, ClientOnlyOptions, DeferredData, RouteContext } from 'olova-router/router';
