import path from 'path';
import type { RouteConfig, NotFoundEntry } from '../types';
import type { LayoutEntry } from '../scanner';

export interface RouteWithExport extends RouteConfig {
  hasDefault: boolean;
  namedExport: string | null;
}

export interface NotFoundWithExport extends NotFoundEntry {
  hasDefault: boolean;
  namedExport: string | null;
}

export interface LayoutWithExport extends LayoutEntry {
  hasDefault: boolean;
  namedExport: string | null;
}

export function generateRouteTree(
  routes: RouteWithExport[], 
  notFoundPages: NotFoundWithExport[], 
  layouts: LayoutWithExport[],
  srcDir: string
): string {
  const routeImports = routes.map((route, index) => {
    const relativePath = './' + path.relative(srcDir, route.component).replace(/\\/g, '/').replace(/\.tsx?$/, '');
    
    if (route.hasDefault) {
      return `import Route${index} from '${relativePath}';`;
    } else if (route.namedExport) {
      return `import { ${route.namedExport} as Route${index} } from '${relativePath}';`;
    } else {
      return `import Route${index} from '${relativePath}';`;
    }
  }).join('\n');

  const notFoundImports = notFoundPages.map((nf, index) => {
    const relativePath = './' + path.relative(srcDir, nf.filePath).replace(/\\/g, '/').replace(/\.tsx?$/, '');
    
    if (nf.hasDefault) {
      return `import NotFound${index} from '${relativePath}';`;
    } else if (nf.namedExport) {
      return `import { ${nf.namedExport} as NotFound${index} } from '${relativePath}';`;
    } else {
      return `import NotFound${index} from '${relativePath}';`;
    }
  }).join('\n');

  const layoutImports = layouts.map((layout, index) => {
    const relativePath = './' + path.relative(srcDir, layout.filePath).replace(/\\/g, '/').replace(/\.tsx?$/, '');
    
    if (layout.hasDefault) {
      return `import Layout${index} from '${relativePath}';`;
    } else if (layout.namedExport) {
      return `import { ${layout.namedExport} as Layout${index} } from '${relativePath}';`;
    } else {
      return `import Layout${index} from '${relativePath}';`;
    }
  }).join('\n');

  const routeObjects = routes.map((route, index) => {
    return `  { path: '${route.path}', component: Route${index} }`;
  }).join(',\n');

  const notFoundObjects = notFoundPages.map((nf, index) => {
    return `  { pathPrefix: '${nf.pathPrefix}', component: NotFound${index} }`;
  }).join(',\n');

  const layoutObjects = layouts.map((layout, index) => {
    return `  { path: '${layout.path}', layout: Layout${index}, children: [] }`;
  }).join(',\n');

  const routePaths = routes.length > 0 ? routes.map(r => `'${r.path}'`).join(' | ') : 'never';

  const allImports = [routeImports, notFoundImports, layoutImports].filter(Boolean).join('\n');

  return `// Auto-generated by olova-router - DO NOT EDIT
// This file is auto-updated when you add/remove route folders

import { createLink, OlovaRouter, useRouter, useParams, useSearchParams, Outlet } from 'olova-router/router';
${allImports}

export const routes = [
${routeObjects || ''}
];

export const notFoundPages = [
${notFoundObjects || ''}
];

export const layouts = [
${layoutObjects || ''}
];

export type RoutePaths = ${routePaths};

export const Link = createLink<RoutePaths>();
export { OlovaRouter, useRouter, useParams, useSearchParams, Outlet };
export type { NotFoundPageConfig, SearchParams, SetSearchParamsOptions, LayoutRoute } from 'olova-router/router';
`;
}
